spring:
  application:
    name: dinedecider

  datasource:
    url: jdbc:postgresql://<<db_host>>:<<db_port>>/<<db_name>>
    username: <<db_user>>
    password: <<db_password>>
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: false

logging:
  level:
    org.hibernate.orm.jdbc.bind: ERROR