version: '3.8'

services:
  app:
    image: dinedecider:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dinedb
      - SPRING_DATASOURCE_USERNAME=dineuser
      - SPRING_DATASOURCE_PASSWORD=dinepassword
    depends_on:
      - db

  db:
    image: postgres:16.3-alpine3.19
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dinedb
      - POSTGRES_USER=dineuser
      - POSTGRES_PASSWORD=dinepassword
    volumes:
      - ./data/schema.sql:/docker-entrypoint-initdb.d/init.sql